package cn.com.scitc.project.mapper;

import cn.com.scitc.project.model.Signin;
import java.util.List;

public interface SigninMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    int insert(Signin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    Signin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    List<Signin> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    int updateByPrimaryKey(Signin record);
}