package cn.com.scitc.webapp1901.model;

import java.math.BigDecimal;
import java.util.Date;

public class Signin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.id
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.studentId
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    private String studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.signDatetime
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    private Date signdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.signDate
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    private Date signdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.temperature
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    private BigDecimal temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.working
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    private Integer working;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.hadTravel
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    private Integer hadtravel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.address
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.jkt
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    private Integer jkt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.jktColor
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    private String jktcolor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.id
     *
     * @return the value of signin.id
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.id
     *
     * @param id the value for signin.id
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.studentId
     *
     * @return the value of signin.studentId
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.studentId
     *
     * @param studentid the value for signin.studentId
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.signDatetime
     *
     * @return the value of signin.signDatetime
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public Date getSigndatetime() {
        return signdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.signDatetime
     *
     * @param signdatetime the value for signin.signDatetime
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public void setSigndatetime(Date signdatetime) {
        this.signdatetime = signdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.signDate
     *
     * @return the value of signin.signDate
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public Date getSigndate() {
        return signdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.signDate
     *
     * @param signdate the value for signin.signDate
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public void setSigndate(Date signdate) {
        this.signdate = signdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.temperature
     *
     * @return the value of signin.temperature
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public BigDecimal getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.temperature
     *
     * @param temperature the value for signin.temperature
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public void setTemperature(BigDecimal temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.working
     *
     * @return the value of signin.working
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public Integer getWorking() {
        return working;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.working
     *
     * @param working the value for signin.working
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public void setWorking(Integer working) {
        this.working = working;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.hadTravel
     *
     * @return the value of signin.hadTravel
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public Integer getHadtravel() {
        return hadtravel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.hadTravel
     *
     * @param hadtravel the value for signin.hadTravel
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public void setHadtravel(Integer hadtravel) {
        this.hadtravel = hadtravel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.address
     *
     * @return the value of signin.address
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.address
     *
     * @param address the value for signin.address
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.jkt
     *
     * @return the value of signin.jkt
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public Integer getJkt() {
        return jkt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.jkt
     *
     * @param jkt the value for signin.jkt
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public void setJkt(Integer jkt) {
        this.jkt = jkt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.jktColor
     *
     * @return the value of signin.jktColor
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public String getJktcolor() {
        return jktcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.jktColor
     *
     * @param jktcolor the value for signin.jktColor
     *
     * @mbg.generated Wed Apr 21 16:26:08 CST 2021
     */
    public void setJktcolor(String jktcolor) {
        this.jktcolor = jktcolor;
    }
}