package cn.com.scitc.studentmanagement.mapper;

import cn.com.scitc.studentmanagement.model.Token;
import java.util.List;

public interface TokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    int insert(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    Token selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    List<Token> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    int updateByPrimaryKey(Token record);
}