package cn.com.scitc.project.model;

import java.util.Date;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.id
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.loginId
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    private String loginid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.realName
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.pwd
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.loginCount
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    private Integer logincount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.lastLoginDt
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    private Date lastlogindt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.id
     *
     * @return the value of manager.id
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.id
     *
     * @param id the value for manager.id
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.loginId
     *
     * @return the value of manager.loginId
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    public String getLoginid() {
        return loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.loginId
     *
     * @param loginid the value for manager.loginId
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    public void setLoginid(String loginid) {
        this.loginid = loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.realName
     *
     * @return the value of manager.realName
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.realName
     *
     * @param realname the value for manager.realName
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.pwd
     *
     * @return the value of manager.pwd
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.pwd
     *
     * @param pwd the value for manager.pwd
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.loginCount
     *
     * @return the value of manager.loginCount
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    public Integer getLogincount() {
        return logincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.loginCount
     *
     * @param logincount the value for manager.loginCount
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    public void setLogincount(Integer logincount) {
        this.logincount = logincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.lastLoginDt
     *
     * @return the value of manager.lastLoginDt
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    public Date getLastlogindt() {
        return lastlogindt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.lastLoginDt
     *
     * @param lastlogindt the value for manager.lastLoginDt
     *
     * @mbg.generated Thu Jun 24 15:20:20 CST 2021
     */
    public void setLastlogindt(Date lastlogindt) {
        this.lastlogindt = lastlogindt;
    }
}