package cn.com.scitc.webapp4.mapper;

import cn.com.scitc.webapp4.pojo.Manager;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Jul 12 14:38:58 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Jul 12 14:38:58 CST 2021
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Jul 12 14:38:58 CST 2021
     */
    Manager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Jul 12 14:38:58 CST 2021
     */
    List<Manager> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Jul 12 14:38:58 CST 2021
     */
    int updateByPrimaryKey(Manager record);
}