package cn.com.scitc.studentmanagement.model;

import java.util.Date;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.id
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.userName
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.realName
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.pwd
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.introduction
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.avatar
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.lastLoginDt
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    private Date lastlogindt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.id
     *
     * @return the value of manager.id
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.id
     *
     * @param id the value for manager.id
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.userName
     *
     * @return the value of manager.userName
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.userName
     *
     * @param username the value for manager.userName
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.realName
     *
     * @return the value of manager.realName
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.realName
     *
     * @param realname the value for manager.realName
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.pwd
     *
     * @return the value of manager.pwd
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.pwd
     *
     * @param pwd the value for manager.pwd
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.introduction
     *
     * @return the value of manager.introduction
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.introduction
     *
     * @param introduction the value for manager.introduction
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.avatar
     *
     * @return the value of manager.avatar
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.avatar
     *
     * @param avatar the value for manager.avatar
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.lastLoginDt
     *
     * @return the value of manager.lastLoginDt
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public Date getLastlogindt() {
        return lastlogindt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.lastLoginDt
     *
     * @param lastlogindt the value for manager.lastLoginDt
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public void setLastlogindt(Date lastlogindt) {
        this.lastlogindt = lastlogindt;
    }

    @Override
    public String toString() {
        return "Manager{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", realname='" + realname + '\'' +
                ", pwd='" + pwd + '\'' +
                ", introduction='" + introduction + '\'' +
                ", avatar='" + avatar + '\'' +
                ", lastlogindt=" + lastlogindt +
                '}';
    }
}