package cn.com.scitc.studentmanagement.model;

import org.springframework.stereotype.Repository;

@Repository
public class Token {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.id
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.userName
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.token
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.id
     *
     * @return the value of token.id
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.id
     *
     * @param id the value for token.id
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.userName
     *
     * @return the value of token.userName
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.userName
     *
     * @param username the value for token.userName
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.token
     *
     * @return the value of token.token
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.token
     *
     * @param token the value for token.token
     *
     * @mbg.generated Tue Jul 20 14:47:06 CST 2021
     */
    public void setToken(String token) {
        this.token = token;
    }
}