# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test05RePsd():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_05RePsd(self):
    # Test name: 05RePsd
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://122.9.143.225/")
    # 2 | setWindowSize | 1259x1080 | 
    self.driver.set_window_size(1259, 1080)
    # 3 | click | linkText=人力资源 | 
    self.driver.find_element(By.LINK_TEXT, "人力资源").click()
    # 4 | click | linkText=企业员工 | 
    self.driver.find_element(By.LINK_TEXT, "企业员工").click()
    # 5 | mouseOver | linkText=企业员工 | 
    element = self.driver.find_element(By.LINK_TEXT, "企业员工")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | mouseOut | linkText=企业员工 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 7 | selectFrame | index=2 | 
    self.driver.switch_to.frame(2)
    # 8 | click | css=.layui-table-hover > td:nth-child(1) .layui-btn-danger | 
    self.driver.find_element(By.CSS_SELECTOR, ".layui-table-hover > td:nth-child(1) .layui-btn-danger").click()
    # 9 | click | linkText=确定 | 
    self.driver.find_element(By.LINK_TEXT, "确定").click()
  
