# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test01Login():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_01Login(self):
    # Test name: 01Login
    # Step # | name | target | value
    # 1 | open | /home/login/index.html | 
    self.driver.get("http://122.9.143.225/home/login/index.html")
    # 2 | setWindowSize | 1259x1080 | 
    self.driver.set_window_size(1259, 1080)
    # 3 | click | name=username | 
    self.driver.find_element(By.NAME, "username").click()
    # 4 | type | name=username | lishuang
    self.driver.find_element(By.NAME, "username").send_keys("lishuang")
    # 5 | click | name=password | 
    self.driver.find_element(By.NAME, "password").click()
    # 6 | type | name=password | 123456
    self.driver.find_element(By.NAME, "password").send_keys("123456")
    # 7 | click | name=captcha | 
    self.driver.find_element(By.NAME, "captcha").click()
    # 8 | type | name=captcha | 26
    self.driver.find_element(By.NAME, "captcha").send_keys("26")
    # 9 | click | id=login-submit | 
    self.driver.find_element(By.ID, "login-submit").click()
    # 10 | mouseOver | id=login-submit | 
    element = self.driver.find_element(By.ID, "login-submit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 11 | mouseOut | id=login-submit | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
