# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test03AddDept():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_03AddDept(self):
    # Test name: 03AddDept
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://122.9.143.225/")
    # 2 | setWindowSize | 1259x1080 | 
    self.driver.set_window_size(1259, 1080)
    # 3 | click | linkText=人力资源 | 
    self.driver.find_element(By.LINK_TEXT, "人力资源").click()
    # 4 | click | linkText=部门架构 | 
    self.driver.find_element(By.LINK_TEXT, "部门架构").click()
    # 5 | selectFrame | index=1 | 
    self.driver.switch_to.frame(1)
    # 6 | click | css=.layui-btn-sm | 
    self.driver.find_element(By.CSS_SELECTOR, ".layui-btn-sm").click()
    # 7 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 8 | click | name=title | 
    self.driver.find_element(By.NAME, "title").click()
    # 9 | type | name=title | 测试
    self.driver.find_element(By.NAME, "title").send_keys("测试")
    # 10 | click | css=.layui-btn-normal | 
    self.driver.find_element(By.CSS_SELECTOR, ".layui-btn-normal").click()
  
